[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rethink"
version = "0.1.0"
description = "Rethink Core module package"
authors = [{name = "fiandev", email = "alfiansa@proton.me"}]
dependencies = []

[project.optional-dependencies]
dev = ["pytest", "black", "flake8"]

[tool.setuptools.packages.find]
where = ["src"]